# gf pack config packed/config.go


# gf home site cdn.
[cdn]
    url = "https://codeload.github.com/qinyuguang/gf-empty/zip/master"

# home site url.
[home]
    url = "https://goframe.org"

# go proxy for gf get.
[proxy]
    urls = [
		"https://goproxy.io/",
		"https://goproxy.cn/"
	]
